//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.12 at 09:33:27 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.shaga.com/soappoc/loanEligibility")
package com.shaga.soappoc.loanEligibility;
